"""
openfoam/case_generator.py

Generates a complete reactingFoam OpenFOAM case directory for a 3D ALD
showerhead simulation.

Solver: reactingFoam  (compressible, reacting, laminar + k-ω SST turbulence)
Physics covered:
  - Flow:    incompressible limit via low-Ma reactingFoam
  - Heat:    energy equation → T field → Nu, h, Bi
  - Species: TMA precursor (Yi) with first-order surface reaction
  - Turbulence: laminar (Re<2300) or k-ω SST (Re>=2300), auto-selected
  - ALD timing: time-varying inlet BC for pulse/purge cycle

Fluid domain topology (z=0 = wafer plane, flow goes downward -z):
    inlet      : top face (gas enters)
    outlet     : bottom face (wafer plane, gas exits radially)
    outerWalls : outer cylinder (no-slip)
    nozzle_walls : nozzle bores through faceplate (no-slip, reaction site)
    plenum_walls : faceplate surfaces (no-slip)
    standoff_walls : standoff region walls (no-slip)
    wafer      : deposition surface (no-slip, reaction site)

Usage
-----
    from openfoam.case_generator import generate_case
    from geometry.parametric import build_showerhead

    geo = build_showerhead({"D": 0.002, "pitch_over_D": 4.0})
    generate_case(geo, "openfoam/cases/case_001",
                  flow_rate_slm=2.0, beta=0.05, T_inlet=393.0)
"""

from __future__ import annotations

import json
import math
import shutil
from pathlib import Path
from typing import Optional

import numpy as np

from geometry.mesh_export import export_stl
from geometry.parametric import ShowerheadGeometry
from geometry.vices.tagger import REGION_WALL, REGION_INLET, REGION_NOZZLE, REGION_WAFER


# ── Physical constants — N2 carrier at 120 °C (393 K), 1 atm ─────────────
RHO_N2   = 1.12      # kg/m³
MU_N2    = 2.0e-5    # Pa·s  dynamic viscosity
NU_N2    = MU_N2 / RHO_N2          # m²/s  kinematic viscosity
CP_N2    = 1040.0    # J/(kg·K)
K_N2     = 0.031     # W/(m·K) thermal conductivity
PR_N2    = CP_N2 * MU_N2 / K_N2    # Prandtl number
D_TMA_N2 = 2.5e-5    # m²/s   TMA diffusivity in N2
A_SOUND  = 380.0     # m/s   speed of sound at 393 K
T_REF    = 393.0     # K     reference temperature (120 °C)
RE_TURB  = 2300.0    # transition Re threshold


# ══════════════════════════════════════════════════════════════════════════
# Helper functions
# ══════════════════════════════════════════════════════════════════════════

def _flow_rate_to_velocity(flow_rate_slm: float, D_plate: float) -> float:
    Q_m3s   = flow_rate_slm * 1e-3 / 60.0
    A_inlet = math.pi * (D_plate / 2.0) ** 2
    return Q_m3s / A_inlet


def _nozzle_velocity(flow_rate_slm: float, D: float, n_holes: int) -> float:
    Q_m3s    = flow_rate_slm * 1e-3 / 60.0
    A_nozzle = n_holes * math.pi * (D / 2.0) ** 2
    return Q_m3s / A_nozzle


def _reynolds(U: float, D: float) -> float:
    return RHO_N2 * U * D / MU_N2


def _is_float_dir(name: str) -> bool:
    try:
        float(name)
        return True
    except ValueError:
        return False


def _is_turbulent(U_nozzle: float, D: float) -> bool:
    return _reynolds(U_nozzle, D) >= RE_TURB


_FOAM_HEADER = """\
/*--------------------------------*- C++ -*----------------------------------*\\
| Generated by cfd-ald-app/openfoam/case_generator.py                        |
\\*---------------------------------------------------------------------------*/
FoamFile
{{
    version     2.0;
    format      ascii;
    class       {cls};
    location    "{location}";
    object      {obj};
}}
"""

def _header(cls: str, location: str, obj: str) -> str:
    return _FOAM_HEADER.format(cls=cls, location=location, obj=obj)


# ══════════════════════════════════════════════════════════════════════════
# system/ files
# ══════════════════════════════════════════════════════════════════════════

def _blockMeshDict(geo: ShowerheadGeometry) -> str:
    p       = geo.params
    R       = p["D_plate"] / 2.0
    z_total = p["standoff"] + p["t_face"] + p["H_plenum"]
    nx      = max(20, int(2 * R / 0.003))
    ny      = nx
    nz      = max(10, int(z_total / 0.003))

    return _header("dictionary", "system", "blockMeshDict") + f"""
scale 1;

vertices
(
    ({-R:.6f} {-R:.6f} 0)              // 0
    ( {R:.6f} {-R:.6f} 0)              // 1
    ( {R:.6f}  {R:.6f} 0)              // 2
    ({-R:.6f}  {R:.6f} 0)              // 3
    ({-R:.6f} {-R:.6f} {z_total:.6f})  // 4
    ( {R:.6f} {-R:.6f} {z_total:.6f})  // 5
    ( {R:.6f}  {R:.6f} {z_total:.6f})  // 6
    ({-R:.6f}  {R:.6f} {z_total:.6f})  // 7
);

blocks
(
    hex (0 1 2 3 4 5 6 7) ({nx} {ny} {nz}) simpleGrading (1 1 1)
);

edges ();

boundary
(
    inlet
    {{
        type patch;
        faces ( (4 5 6 7) );
    }}
    outlet
    {{
        type patch;
        faces ( (0 1 2 3) );
    }}
    outerWalls
    {{
        type wall;
        faces
        (
            (0 1 5 4)
            (1 2 6 5)
            (2 3 7 6)
            (3 0 4 7)
        );
    }}
);

mergePatchPairs ();
"""


def _snappyHexMeshDict(geo: ShowerheadGeometry) -> str:
    p        = geo.params
    D        = p["D"]
    t_face   = p["t_face"]
    standoff = p["standoff"]
    H_plenum = p["H_plenum"]
    z_total  = standoff + t_face + H_plenum

    nozzle_level = max(2, int(math.log2(0.003 / D)) + 1)
    plate_level  = max(1, nozzle_level - 1)

    inside_z = standoff + t_face + H_plenum * 0.5

    return _header("dictionary", "system", "snappyHexMeshDict") + f"""
castellatedMesh true;
snap            true;
addLayers       false;

geometry
{{
    nozzles.stl      {{ type triSurfaceMesh; name nozzle_walls; }}
    plenum.stl       {{ type triSurfaceMesh; name plenum_walls; }}
    standoff.stl     {{ type triSurfaceMesh; name standoff_walls; }}
    wafer_plane.stl  {{ type triSurfaceMesh; name wafer; }}
}}

castellatedMeshControls
{{
    maxLocalCells           1000000;
    maxGlobalCells          3000000;
    minRefinementCells      10;
    maxLoadUnbalance        0.10;
    nCellsBetweenLevels     1;
    resolveFeatureAngle     30;

    features ();

    refinementSurfaces
    {{
        nozzle_walls   {{ level ({nozzle_level} {nozzle_level}); patchInfo {{ type wall; }} }}
        plenum_walls   {{ level ({plate_level}  {plate_level});  patchInfo {{ type wall; }} }}
        standoff_walls {{ level ({plate_level}  {plate_level});  patchInfo {{ type wall; }} }}
        wafer          {{ level ({plate_level}  {plate_level});  patchInfo {{ type wall; }} }}
    }}

    refinementRegions {{}}
    locationInMesh (0 0 {inside_z:.4f});
    allowFreeStandingZoneFaces true;
}}

snapControls
{{
    nSmoothPatch        3;
    tolerance           2.0;
    nSolveIter          10;
    nRelaxIter          3;
    nFeatureSnapIter    10;
    implicitFeatureSnap false;
    explicitFeatureSnap true;
    multiRegionFeatureSnap false;
}}

addLayersControls
{{
    relativeSizes       true;
    layers {{}}
    expansionRatio      1.2;
    finalLayerThickness 0.3;
    minThickness        0.1;
    nGrow               0;
    featureAngle        60;
    nRelaxIter          3;
    nSmoothSurfaceNormals 1;
    nSmoothNormals      3;
    nSmoothThickness    10;
    maxFaceThicknessRatio 0.5;
    maxThicknessToMedialRatio 0.3;
    minMedialAxisAngle  90;
    nBufferCellsNoExtrude 0;
    nLayerIter          50;
}}

meshQualityControls
{{
    maxNonOrtho         65;
    maxBoundarySkewness 20;
    maxInternalSkewness 4;
    maxConcave          80;
    minVol              1e-13;
    minTetQuality       1e-30;
    minArea             -1;
    minTwist            0.02;
    minDeterminant      0.001;
    minFaceWeight       0.05;
    minVolRatio         0.01;
    minTriangleTwist    -1;
    nSmoothScale        4;
    errorReduction      0.75;
    relaxed {{ maxNonOrtho 75; }}
}}

writeFlags ( scalarLevels );
mergeTolerance 1e-6;
"""


def _controlDict(pulse_time: float, purge_time: float, dt: float = 1e-4) -> str:
    end_time = pulse_time + purge_time + 0.05
    return _header("dictionary", "system", "controlDict") + f"""
application     reactingFoam;

startFrom       startTime;
startTime       0;
stopAt          endTime;
endTime         {end_time:.4f};

deltaT          {dt:.2e};

writeControl    adjustableRunTime;
writeInterval   {pulse_time / 5:.4f};

purgeWrite      0;
writeFormat     ascii;
writePrecision  8;
writeCompression off;

timeFormat      general;
timePrecision   6;

runTimeModifiable yes;
adjustTimeStep  yes;
maxCo           0.5;
maxDeltaT       {dt * 10:.2e};
"""


def _fvSchemes(turbulent: bool) -> str:
    div_k    = "Gauss linearUpwind grad(k);"     if turbulent else ""
    div_omega= "Gauss linearUpwind grad(omega);" if turbulent else ""
    return _header("dictionary", "system", "fvSchemes") + f"""
ddtSchemes      {{ default Euler; }}

gradSchemes     {{ default Gauss linear; }}

divSchemes
{{
    default                         none;
    div(phi,U)                      Gauss linearUpwind grad(U);
    div(phi,Yi_h)                   Gauss limitedLinear 1;
    div(phi,h)                      Gauss linearUpwind grad(h);
    div(phi,K)                      Gauss linearUpwind grad(K);
    div(phi,epsilon)                Gauss linearUpwind grad(epsilon);
{"    div(phi,k)                      " + div_k if div_k else ""}
{"    div(phi,omega)                  " + div_omega if div_omega else ""}
    div((nuEff*dev2(T(grad(U)))))   Gauss linear;
    div(((rho*nuEff)*dev2(T(grad(U))))) Gauss linear;
}}

laplacianSchemes {{ default Gauss linear corrected; }}

interpolationSchemes {{ default linear; }}

snGradSchemes {{ default corrected; }}

fluxRequired
{{
    default     no;
    p_rgh       ;
    p           ;
}}
"""


def _fvSolution(turbulent: bool) -> str:
    turb_solvers = """
    k
    {
        solver          PBiCGStab;
        preconditioner  DILU;
        tolerance       1e-8;
        relTol          0.1;
    }
    omega
    {
        solver          PBiCGStab;
        preconditioner  DILU;
        tolerance       1e-8;
        relTol          0.1;
    }""" if turbulent else ""

    turb_relax = """
        k               0.7;
        omega           0.7;""" if turbulent else ""

    return _header("dictionary", "system", "fvSolution") + f"""
solvers
{{
    p
    {{
        solver          PCG;
        preconditioner  DIC;
        tolerance       1e-8;
        relTol          0.01;
    }}
    pFinal  {{ $p; relTol 0; }}

    "(rho|rhoFinal)"
    {{
        solver          diagonal;
    }}

    U
    {{
        solver          PBiCGStab;
        preconditioner  DILU;
        tolerance       1e-8;
        relTol          0.1;
    }}
    UFinal  {{ $U; relTol 0; }}

    h
    {{
        solver          PBiCGStab;
        preconditioner  DILU;
        tolerance       1e-8;
        relTol          0.1;
    }}
    hFinal  {{ $h; relTol 0; }}

    Yi
    {{
        solver          PBiCGStab;
        preconditioner  DILU;
        tolerance       1e-10;
        relTol          0.1;
    }}
    YiFinal  {{ $Yi; relTol 0; }}

    "(TMA|N2)"
    {{
        solver          PBiCGStab;
        preconditioner  DILU;
        tolerance       1e-10;
        relTol          0.1;
    }}
    "(TMA|N2)Final"  {{ $Yi; relTol 0; }}
{turb_solvers}
}}

PIMPLE
{{
    momentumPredictor   yes;
    nOuterCorrectors    2;
    nCorrectors         2;
    nNonOrthogonalCorrectors 1;
    pRefCell            0;
    pRefValue           0;
}}

relaxationFactors
{{
    equations
    {{
        U       0.7;
        h       0.7;
        TMA     0.9;
        N2      0.9;
{turb_relax}
    }}
}}
"""


# ══════════════════════════════════════════════════════════════════════════
# constant/ files
# ══════════════════════════════════════════════════════════════════════════

def _thermophysicalProperties(T_inlet: float) -> str:
    """
    Thermophysical properties for N2 carrier + TMA precursor mixture.
    Using hePsiThermo with janafThermo for temperature-dependent Cp.
    Simplified: treat mixture as N2 with TMA as dilute species.
    """
    return _header("dictionary", "constant", "thermophysicalProperties") + f"""
thermoType
{{
    type            hePsiThermo;
    mixture         multiComponentMixture;
    transport       sutherland;
    thermo          janaf;
    energy          sensibleEnthalpy;
    equationOfState perfectGas;
    specie          specie;
}}

inertSpecie N2;

species
(
    N2
    TMA
);

N2
{{
    specie
    {{
        molWeight   28.014;
    }}
    thermodynamics
    {{
        Tlow            200;
        Thigh           5000;
        Tcommon         1000;
        highCpCoeffs    ( 2.95258 1.39690e-3 -4.92632e-7 7.86010e-11 -4.60755e-15 -923.949 5.87189 );
        lowCpCoeffs     ( 3.53101 -1.23661e-4 -5.02999e-7 2.43531e-9 -1.40881e-12 -1046.98 2.96747 );
    }}
    transport
    {{
        As              1.458e-6;
        Ts              110.4;
    }}
}}

TMA
{{
    // Trimethylaluminium Al(CH3)3 — simplified as heavy hydrocarbon
    specie
    {{
        molWeight   72.086;
    }}
    thermodynamics
    {{
        Tlow            300;
        Thigh           2000;
        Tcommon         1000;
        highCpCoeffs    ( 8.5 0.02 0 0 0 -10000 20 );
        lowCpCoeffs     ( 3.5 0.05 0 0 0  -8000 15 );
    }}
    transport
    {{
        As              2.0e-6;
        Ts              200;
    }}
}}
"""


def _reactions(beta: float, v_th: float, D_m: float) -> str:
    """
    Surface reaction for TMA deposition.
    Rate = beta * v_th / 4 * [TMA]  (first-order Langmuir-Hinshelwood)
    """
    k_surface = beta * v_th / 4.0
    return _header("dictionary", "constant", "reactions") + f"""
// TMA surface deposition reaction
// Rate = k_s * Y_TMA  where k_s = beta * v_th / 4 = {k_surface:.4f} m/s

reactions
{{
    TMAdeposition
    {{
        type            irreversibleSurfaceArrheniusReaction;
        reaction        "TMA = N2";
        A               {k_surface:.4f};
        beta            0;
        Ta              0;
    }}
}}
"""


def _momentumTransport(turbulent: bool) -> str:
    sim_type = "RAS" if turbulent else "laminar"
    ras_block = """
RAS
{
    model           kOmegaSST;
    turbulence      on;
    printCoeffs     on;
}
""" if turbulent else ""

    return _header("dictionary", "constant", "momentumTransport") + f"""
simulationType  {sim_type};
{ras_block}
"""


def _thermophysicalTransport() -> str:
    return _header("dictionary", "constant", "thermophysicalTransport") + f"""
modelType       Fickian;

Prt             {PR_N2:.4f};

Sct             0.7;
"""


# ══════════════════════════════════════════════════════════════════════════
# 0/ boundary condition files
# ══════════════════════════════════════════════════════════════════════════

_WALLS = ["outerWalls", "nozzle_walls", "plenum_walls", "standoff_walls", "wafer"]

def _all_walls(bc_str: str) -> str:
    return "\n".join(f"    {w}  {{ {bc_str} }}" for w in _WALLS)


def _field_U(U_inlet: float) -> str:
    return _header("volVectorField", "0", "U") + f"""
dimensions      [0 1 -1 0 0 0 0];

internalField   uniform (0 0 {-abs(U_inlet):.6f});

boundaryField
{{
    inlet
    {{
        type            fixedValue;
        value           uniform (0 0 {-abs(U_inlet):.6f});
    }}
    outlet
    {{
        type            pressureInletOutletVelocity;
        value           uniform (0 0 0);
    }}
{_all_walls("type noSlip;")}
}}
"""


def _field_p() -> str:
    return _header("volScalarField", "0", "p") + """
dimensions      [1 -1 -2 0 0 0 0];

internalField   uniform 101325;

boundaryField
{
    inlet           { type zeroGradient; }
    outlet          { type fixedValue; value uniform 101325; }
    outerWalls      { type zeroGradient; }
    nozzle_walls    { type zeroGradient; }
    plenum_walls    { type zeroGradient; }
    standoff_walls  { type zeroGradient; }
    wafer           { type zeroGradient; }
}
"""


def _field_T(T_inlet: float) -> str:
    return _header("volScalarField", "0", "T") + f"""
dimensions      [0 0 0 1 0 0 0];

internalField   uniform {T_inlet:.1f};

boundaryField
{{
    inlet
    {{
        type            fixedValue;
        value           uniform {T_inlet:.1f};
    }}
    outlet          {{ type zeroGradient; }}
    outerWalls      {{ type zeroGradient; }}
    nozzle_walls    {{ type zeroGradient; }}
    plenum_walls    {{ type zeroGradient; }}
    standoff_walls  {{ type zeroGradient; }}
    wafer
    {{
        // Wafer held at slightly lower temperature (5K delta typical for ALD)
        type            fixedValue;
        value           uniform {T_inlet - 5.0:.1f};
    }}
}}
"""


def _field_TMA(pulse_time: float) -> str:
    """
    TMA mass fraction — pulsed inlet.
    Pulse: Y_TMA = 0.01 (1% by mass, typical ALD precursor)
    Purge: Y_TMA = 0    (pure N2)
    """
    purge_start = pulse_time
    purge_end   = purge_start + pulse_time * 0.05   # 5% ramp-down

    return _header("volScalarField", "0", "TMA") + f"""
dimensions      [0 0 0 0 0 0 0];

internalField   uniform 0;

boundaryField
{{
    inlet
    {{
        // Time-varying: TMA pulse followed by N2 purge
        type            uniformFixedValue;
        uniformValue    table
        (
            (0                  0    )
            (1e-5               0.01 )
            ({pulse_time:.4f}   0.01 )
            ({purge_end:.4f}    0    )
            (1e6                0    )
        );
    }}
    outlet
    {{
        type            inletOutlet;
        inletValue      uniform 0;
        value           uniform 0;
    }}
    nozzle_walls
    {{
        // First-order surface reaction: TMA adsorbs on nozzle walls
        type            zeroGradient;
    }}
    wafer
    {{
        // Full sticking: TMA consumed at wafer surface
        type            fixedValue;
        value           uniform 0;
    }}
    outerWalls      {{ type zeroGradient; }}
    plenum_walls    {{ type zeroGradient; }}
    standoff_walls  {{ type zeroGradient; }}
}}
"""


def _field_N2() -> str:
    return _header("volScalarField", "0", "N2") + """
dimensions      [0 0 0 0 0 0 0];

internalField   uniform 1;

boundaryField
{
    inlet           { type fixedValue; value uniform 1; }
    outlet          { type inletOutlet; inletValue uniform 1; value uniform 1; }
    outerWalls      { type zeroGradient; }
    nozzle_walls    { type zeroGradient; }
    plenum_walls    { type zeroGradient; }
    standoff_walls  { type zeroGradient; }
    wafer           { type zeroGradient; }
}
"""


def _field_k(U_nozzle: float, D: float) -> str:
    """Turbulent kinetic energy — 5% inlet turbulence intensity."""
    I  = 0.05
    k0 = 1.5 * (U_nozzle * I) ** 2
    return _header("volScalarField", "0", "k") + f"""
dimensions      [0 2 -2 0 0 0 0];

internalField   uniform {k0:.6f};

boundaryField
{{
    inlet
    {{
        type            fixedValue;
        value           uniform {k0:.6f};
    }}
    outlet          {{ type zeroGradient; }}
    outerWalls      {{ type kqRWallFunction; value uniform {k0:.6f}; }}
    nozzle_walls    {{ type kqRWallFunction; value uniform {k0:.6f}; }}
    plenum_walls    {{ type kqRWallFunction; value uniform {k0:.6f}; }}
    standoff_walls  {{ type kqRWallFunction; value uniform {k0:.6f}; }}
    wafer           {{ type kqRWallFunction; value uniform {k0:.6f}; }}
}}
"""


def _field_omega(U_nozzle: float, D: float) -> str:
    """Specific dissipation rate."""
    I    = 0.05
    k0   = 1.5 * (U_nozzle * I) ** 2
    Cmu  = 0.09
    L    = 0.07 * D   # turbulent length scale
    eps0 = Cmu ** 0.75 * k0 ** 1.5 / L
    om0  = eps0 / (Cmu * k0)
    return _header("volScalarField", "0", "omega") + f"""
dimensions      [0 0 -1 0 0 0 0];

internalField   uniform {om0:.4f};

boundaryField
{{
    inlet
    {{
        type            fixedValue;
        value           uniform {om0:.4f};
    }}
    outlet          {{ type zeroGradient; }}
    outerWalls      {{ type omegaWallFunction; value uniform {om0:.4f}; }}
    nozzle_walls    {{ type omegaWallFunction; value uniform {om0:.4f}; }}
    plenum_walls    {{ type omegaWallFunction; value uniform {om0:.4f}; }}
    standoff_walls  {{ type omegaWallFunction; value uniform {om0:.4f}; }}
    wafer           {{ type omegaWallFunction; value uniform {om0:.4f}; }}
}}
"""


# ══════════════════════════════════════════════════════════════════════════
# Case metadata
# ══════════════════════════════════════════════════════════════════════════

def _write_case_json(case_dir: Path, geo: ShowerheadGeometry,
                     flow_rate_slm: float, beta: float, v_th: float,
                     D_m: float, T_inlet: float,
                     pulse_time: float, purge_time: float,
                     turbulent: bool):
    from physics.calculator import (
        reynolds, prandtl, schmidt, mach,
        peclet_heat, peclet_mass, damkohler, k_rxn_from_sticking,
    )
    p        = geo.params
    U_nozzle = _nozzle_velocity(flow_rate_slm, p["D"], geo.n_holes)
    k_rxn    = k_rxn_from_sticking(beta, v_th)
    Re       = reynolds(RHO_N2, U_nozzle, p["D"], MU_N2)
    Pr       = prandtl(CP_N2, MU_N2, K_N2)
    Sc       = schmidt(MU_N2, RHO_N2, D_m)

    meta = {
        "solver":  "reactingFoam",
        "turbulence": "kOmegaSST" if turbulent else "laminar",
        "geometry": p,
        "n_holes":  geo.n_holes,
        "pattern":  geo.topology.pattern.value,
        "open_area": geo.open_area_frac,
        "process": {
            "flow_rate_slm": flow_rate_slm,
            "beta":          beta,
            "v_th":          v_th,
            "D_m":           D_m,
            "T_inlet":       T_inlet,
            "pulse_time":    pulse_time,
            "purge_time":    purge_time,
        },
        "dimensionless": {
            "Re":   Re,
            "Pr":   Pr,
            "Sc":   Sc,
            "Ma":   mach(U_nozzle, A_SOUND),
            "Pe_h": peclet_heat(Re, Pr),
            "Pe_m": peclet_mass(Re, Sc),
            "Da":   damkohler(k_rxn, p["D"], U_nozzle),
        },
    }
    with open(case_dir / "case_meta.json", "w") as f:
        json.dump(meta, f, indent=2)


# ══════════════════════════════════════════════════════════════════════════
# Main entry point
# ══════════════════════════════════════════════════════════════════════════

def generate_case(
    geo:           ShowerheadGeometry,
    case_dir:      str,
    flow_rate_slm: float = 2.0,
    beta:          float = 0.05,
    v_th:          float = 144.0,
    D_m:           float = D_TMA_N2,
    T_inlet:       float = T_REF,
    pulse_time:    float = 0.10,
    purge_time:    float = 0.10,
    dt:            float = 1e-4,
) -> str:
    """
    Generate a complete reactingFoam OpenFOAM case directory.

    Turbulence model is auto-selected:
      Re < 2300  → laminar
      Re >= 2300 → k-ω SST
    """
    p          = geo.params
    out        = Path(case_dir)
    U_inlet    = _flow_rate_to_velocity(flow_rate_slm, p["D_plate"])
    U_nozzle   = _nozzle_velocity(flow_rate_slm, p["D"], geo.n_holes)
    turbulent  = _is_turbulent(U_nozzle, p["D"])
    Re         = _reynolds(U_nozzle, p["D"])

    if out.exists():
        # Never wipe a case that already has solver output
        _has_results = any(
            True for d in out.iterdir()
            if d.is_dir() and d.name not in ("0", "constant", "system", "geometry")
            and _is_float_dir(d.name) and float(d.name) > 0
            and (d / "U").exists()
        )
        if _has_results:
            return  # Case already solved — do not overwrite
        shutil.rmtree(out)

    # Directory structure
    (out / "0").mkdir(parents=True)
    (out / "constant" / "polyMesh").mkdir(parents=True)
    (out / "system").mkdir(parents=True)
    (out / "geometry").mkdir(parents=True)

    # ── 0/ fields ────────────────────────────────────────────────────────
    (out / "0" / "U").write_text(_field_U(U_inlet))
    (out / "0" / "p").write_text(_field_p())
    (out / "0" / "T").write_text(_field_T(T_inlet))
    (out / "0" / "TMA").write_text(_field_TMA(pulse_time))
    (out / "0" / "N2").write_text(_field_N2())

    if turbulent:
        (out / "0" / "k").write_text(_field_k(U_nozzle, p["D"]))
        (out / "0" / "omega").write_text(_field_omega(U_nozzle, p["D"]))

    # ── constant/ ────────────────────────────────────────────────────────
    (out / "constant" / "thermophysicalProperties").write_text(
        _thermophysicalProperties(T_inlet))
    (out / "constant" / "reactions").write_text(
        _reactions(beta, v_th, D_m))
    (out / "constant" / "momentumTransport").write_text(
        _momentumTransport(turbulent))
    (out / "constant" / "turbulenceProperties").write_text(
        _momentumTransport(turbulent).replace('"momentumTransport"', '"turbulenceProperties"'))
    (out / "constant" / "thermophysicalTransport").write_text(
        _thermophysicalTransport())

    # ── system/ ──────────────────────────────────────────────────────────
    (out / "system" / "blockMeshDict").write_text(_blockMeshDict(geo))
    (out / "system" / "controlDict").write_text(
        _controlDict(pulse_time, purge_time, dt))
    (out / "system" / "snappyHexMeshDict").write_text(_snappyHexMeshDict(geo))
    (out / "system" / "fvSchemes").write_text(_fvSchemes(turbulent))
    (out / "system" / "fvSolution").write_text(_fvSolution(turbulent))

    # decomposeParDict from template if available
    src = Path(__file__).parent / "showerhead_3d" / "system" / "decomposeParDict"
    if src.exists():
        shutil.copy(src, out / "system" / "decomposeParDict")

    # ── STL geometry ─────────────────────────────────────────────────────
    export_stl(geo, str(out / "geometry"), combined=False)

    # ── Metadata ─────────────────────────────────────────────────────────
    _write_case_json(out, geo, flow_rate_slm, beta, v_th, D_m,
                     T_inlet, pulse_time, purge_time, turbulent)

    # ── run.sh ───────────────────────────────────────────────────────────
    turb_info = f"k-omega SST (Re={Re:.0f})" if turbulent else f"laminar (Re={Re:.0f})"
    run_sh = f"""#!/bin/bash
# Auto-generated run script — reactingFoam
# Case: {out.name}
# Turbulence: {turb_info}
set -e
cd "$(dirname "$0")"

mkdir -p constant/triSurface
cp geometry/*.stl constant/triSurface/

echo "=== blockMesh ==="
blockMesh

echo "=== snappyHexMesh ==="
snappyHexMesh -overwrite

echo "=== reactingFoam ==="
reactingFoam

echo "=== Done: {out.name} ==="
"""
    run_path = out / "run.sh"
    run_path.write_text(run_sh)
    run_path.chmod(0o755)

    print(f"Case generated: {out}")
    print(f"  Solver:  reactingFoam  |  Turbulence: {turb_info}")
    print(f"  U_inlet: {U_inlet:.4f} m/s  |  U_nozzle: {U_nozzle:.4f} m/s")
    print(f"  beta:    {beta}  |  T_inlet: {T_inlet:.1f} K  |  pulse: {pulse_time}s")
    return str(out)


# ══════════════════════════════════════════════════════════════════════════
# Track 2 — VICES case generator
# ══════════════════════════════════════════════════════════════════════════

def _export_vices_stls(vices_result, geo_dir: Path) -> dict:
    """
    Extract region-specific STLs from VICES trimesh + face tags.
    Returns dict of {region_name: stl_path}.
    """
    import trimesh as _tr

    mesh  = vices_result.mesh
    pts   = vices_result.point_cloud
    tags  = vices_result.node_tags

    # tag mesh faces by majority vote of face centroid tags
    from geometry.vices.tagger import tag_points
    tag_bounds = vices_result.params.get('_tag_bounds', {})
    face_tags  = tag_points(mesh.triangles_center.astype(np.float32),
                             tag_bounds) if tag_bounds else None

    region_map = {
        'vices_inlet':   REGION_INLET,
        'nozzle_walls':  REGION_NOZZLE,
        'wafer':         REGION_WAFER,
        'vices_walls':   REGION_WALL,
    }

    stl_paths = {}
    for name, region_id in region_map.items():
        if face_tags is not None:
            face_mask = face_tags == region_id
        else:
            # fallback: tag faces geometrically from vertex positions
            verts = mesh.vertices
            z = verts[:, 2]
            z_min, z_max = z.min(), z.max()
            fc = mesh.triangles_center
            fz = fc[:, 2]
            if region_id == REGION_INLET:
                face_mask = fz > z_max - (z_max - z_min) * 0.05
            elif region_id == REGION_WAFER:
                face_mask = fz < z_min + (z_max - z_min) * 0.05
            elif region_id == REGION_NOZZLE:
                r = np.sqrt(fc[:, 0]**2 + fc[:, 1]**2)
                D = vices_result.params.get('D', 0.002)
                face_mask = r < D * 0.7
            else:
                face_mask = np.ones(len(mesh.faces), dtype=bool)

        if face_mask.sum() == 0:
            continue

        sub = mesh.submesh([np.where(face_mask)[0]], append=True)
        stl_path = geo_dir / f'{name}.stl'
        sub.export(str(stl_path))
        stl_paths[name] = stl_path

    # always export full mesh as combined fallback
    full_path = geo_dir / 'vices_full.stl'
    mesh.export(str(full_path))
    stl_paths['vices_full'] = full_path

    return stl_paths


def _blockMeshDict_vices(vices_result) -> str:
    """blockMeshDict sized to VICES mesh bounding box + margin."""
    verts  = vices_result.mesh.vertices
    margin = 0.005   # 5 mm margin
    xmin, ymin, zmin = verts.min(axis=0) - margin
    xmax, ymax, zmax = verts.max(axis=0) + margin

    nx = max(20, int((xmax - xmin) / 0.004))
    ny = max(20, int((ymax - ymin) / 0.004))
    nz = max(10, int((zmax - zmin) / 0.003))

    return _header("dictionary", "system", "blockMeshDict") + f"""
scale 1;

vertices
(
    ({xmin:.6f} {ymin:.6f} {zmin:.6f})  // 0
    ({xmax:.6f} {ymin:.6f} {zmin:.6f})  // 1
    ({xmax:.6f} {ymax:.6f} {zmin:.6f})  // 2
    ({xmin:.6f} {ymax:.6f} {zmin:.6f})  // 3
    ({xmin:.6f} {ymin:.6f} {zmax:.6f})  // 4
    ({xmax:.6f} {ymin:.6f} {zmax:.6f})  // 5
    ({xmax:.6f} {ymax:.6f} {zmax:.6f})  // 6
    ({xmin:.6f} {ymax:.6f} {zmax:.6f})  // 7
);

blocks
(
    hex (0 1 2 3 4 5 6 7) ({nx} {ny} {nz}) simpleGrading (1 1 1)
);

edges ();

boundary
(
    inlet
    {{
        type patch;
        faces ( (4 5 6 7) );
    }}
    outlet
    {{
        type patch;
        faces ( (0 1 2 3) );
    }}
    outerWalls
    {{
        type wall;
        faces
        (
            (0 1 5 4)
            (1 2 6 5)
            (2 3 7 6)
            (3 0 4 7)
        );
    }}
);

mergePatchPairs ();
"""


def _snappyHexMeshDict_vices(vices_result, stl_paths: dict) -> str:
    """snappyHexMeshDict using VICES region STLs."""
    verts   = vices_result.mesh.vertices
    D       = vices_result.params.get('D', 0.002)
    z_min   = float(verts[:, 2].min())
    z_max   = float(verts[:, 2].max())
    inside_z = (z_min + z_max) / 2.0   # point inside fluid domain

    nozzle_level = max(2, int(math.log2(0.003 / max(D, 0.0005))) + 1)
    wall_level   = max(1, nozzle_level - 1)

    # build geometry block entries for each region STL that exists
    geo_entries = ""
    refine_entries = ""
    for name, path in stl_paths.items():
        if name == 'vices_full':
            continue
        patch_type = 'wall' if name not in ('vices_inlet',) else 'patch'
        level = nozzle_level if 'nozzle' in name else wall_level
        geo_entries    += f"    {name}.stl  {{ type triSurfaceMesh; name {name}; }}\n"
        refine_entries += (f"        {name}  {{ level ({level} {level}); "
                           f"patchInfo {{ type {patch_type}; }} }}\n")

    return _header("dictionary", "system", "snappyHexMeshDict") + f"""
castellatedMesh true;
snap            true;
addLayers       false;

geometry
{{
{geo_entries}}}

castellatedMeshControls
{{
    maxLocalCells           1000000;
    maxGlobalCells          3000000;
    minRefinementCells      10;
    maxLoadUnbalance        0.10;
    nCellsBetweenLevels     1;
    resolveFeatureAngle     30;

    features ();

    refinementSurfaces
    {{
{refine_entries}    }}

    refinementRegions {{}}
    locationInMesh (0 0 {inside_z:.4f});
    allowFreeStandingZoneFaces true;
}}

snapControls
{{
    nSmoothPatch        3;
    tolerance           2.0;
    nSolveIter          10;
    nRelaxIter          3;
    nFeatureSnapIter    10;
    implicitFeatureSnap false;
    explicitFeatureSnap true;
    multiRegionFeatureSnap false;
}}

addLayersControls
{{
    relativeSizes       true;
    layers {{}}
    expansionRatio      1.2;
    finalLayerThickness 0.3;
    minThickness        0.1;
}}

meshQualityControls
{{
    maxNonOrtho         65;
    maxBoundarySkewness 20;
    maxInternalSkewness 4;
    maxConcave          80;
    minVol              1e-13;
    minTetQuality       1e-30;
    minArea             -1;
    minTwist            0.02;
    minDeterminant      0.001;
    minFaceWeight       0.05;
    minVolRatio         0.01;
    minTriangleTwist    -1;
    nSmoothScale        4;
    errorReduction      0.75;
    relaxed {{ maxNonOrtho 75; }}
}}

writeFlags ( scalarLevels );
mergeTolerance 1e-6;
"""


# ── Track 2 BC writers — use VICES patch names ────────────────────────────
# VICES patches: inlet, outlet, outerWalls (blockMesh)
#                vices_walls, vices_inlet, nozzle_walls, wafer (STL)

_VICES_WALLS = ["outerWalls", "vices_walls", "vices_inlet"]

def _v2_field_U(U_inlet: float) -> str:
    return _header("volVectorField", "0", "U") + f"""
dimensions      [0 1 -1 0 0 0 0];
internalField   uniform (0 0 {-abs(U_inlet):.6f});
boundaryField
{{
    inlet           {{ type fixedValue; value uniform (0 0 {-abs(U_inlet):.6f}); }}
    outlet          {{ type pressureInletOutletVelocity; value uniform (0 0 0); }}
    outerWalls      {{ type noSlip; }}
    vices_walls     {{ type noSlip; }}
    vices_inlet     {{ type noSlip; }}
    nozzle_walls    {{ type noSlip; }}
    wafer           {{ type noSlip; }}
}}
"""

def _v2_field_p() -> str:
    return _header("volScalarField", "0", "p") + """
dimensions      [1 -1 -2 0 0 0 0];
internalField   uniform 101325;
boundaryField
{
    inlet           { type zeroGradient; }
    outlet          { type fixedValue; value uniform 101325; }
    outerWalls      { type zeroGradient; }
    vices_walls     { type zeroGradient; }
    vices_inlet     { type zeroGradient; }
    nozzle_walls    { type zeroGradient; }
    wafer           { type zeroGradient; }
}
"""

def _v2_field_T(T_inlet: float) -> str:
    return _header("volScalarField", "0", "T") + f"""
dimensions      [0 0 0 1 0 0 0];
internalField   uniform {T_inlet:.1f};
boundaryField
{{
    inlet           {{ type fixedValue; value uniform {T_inlet:.1f}; }}
    outlet          {{ type zeroGradient; }}
    outerWalls      {{ type zeroGradient; }}
    vices_walls     {{ type zeroGradient; }}
    vices_inlet     {{ type zeroGradient; }}
    nozzle_walls    {{ type zeroGradient; }}
    wafer           {{ type fixedValue; value uniform {T_inlet - 5.0:.1f}; }}
}}
"""

def _v2_field_TMA(pulse_time: float) -> str:
    purge_end = pulse_time + pulse_time * 0.05
    return _header("volScalarField", "0", "TMA") + f"""
dimensions      [0 0 0 0 0 0 0];
internalField   uniform 0;
boundaryField
{{
    inlet
    {{
        type            uniformFixedValue;
        uniformValue    table
        (
            (0                  0    )
            (1e-5               0.01 )
            ({pulse_time:.4f}   0.01 )
            ({purge_end:.4f}    0    )
            (1e6                0    )
        );
    }}
    outlet          {{ type inletOutlet; inletValue uniform 0; value uniform 0; }}
    outerWalls      {{ type zeroGradient; }}
    vices_walls     {{ type zeroGradient; }}
    vices_inlet     {{ type zeroGradient; }}
    nozzle_walls    {{ type zeroGradient; }}
    wafer           {{ type fixedValue; value uniform 0; }}
}}
"""

def _v2_field_N2() -> str:
    return _header("volScalarField", "0", "N2") + """
dimensions      [0 0 0 0 0 0 0];
internalField   uniform 1;
boundaryField
{
    inlet           { type fixedValue; value uniform 1; }
    outlet          { type inletOutlet; inletValue uniform 1; value uniform 1; }
    outerWalls      { type zeroGradient; }
    vices_walls     { type zeroGradient; }
    vices_inlet     { type zeroGradient; }
    nozzle_walls    { type zeroGradient; }
    wafer           { type zeroGradient; }
}
"""

def _v2_field_k(U_nozzle: float, D: float) -> str:
    I  = 0.05
    k0 = 1.5 * (U_nozzle * I) ** 2
    return _header("volScalarField", "0", "k") + f"""
dimensions      [0 2 -2 0 0 0 0];
internalField   uniform {k0:.6f};
boundaryField
{{
    inlet           {{ type fixedValue; value uniform {k0:.6f}; }}
    outlet          {{ type zeroGradient; }}
    outerWalls      {{ type kqRWallFunction; value uniform {k0:.6f}; }}
    vices_walls     {{ type kqRWallFunction; value uniform {k0:.6f}; }}
    vices_inlet     {{ type kqRWallFunction; value uniform {k0:.6f}; }}
    nozzle_walls    {{ type kqRWallFunction; value uniform {k0:.6f}; }}
    wafer           {{ type kqRWallFunction; value uniform {k0:.6f}; }}
}}
"""

def _v2_field_omega(U_nozzle: float, D: float) -> str:
    I    = 0.05
    k0   = 1.5 * (U_nozzle * I) ** 2
    Cmu  = 0.09
    L    = 0.07 * D
    eps0 = Cmu ** 0.75 * k0 ** 1.5 / L
    om0  = eps0 / (Cmu * k0)
    return _header("volScalarField", "0", "omega") + f"""
dimensions      [0 0 -1 0 0 0 0];
internalField   uniform {om0:.4f};
boundaryField
{{
    inlet           {{ type fixedValue; value uniform {om0:.4f}; }}
    outlet          {{ type zeroGradient; }}
    outerWalls      {{ type omegaWallFunction; value uniform {om0:.4f}; }}
    vices_walls     {{ type omegaWallFunction; value uniform {om0:.4f}; }}
    vices_inlet     {{ type omegaWallFunction; value uniform {om0:.4f}; }}
    nozzle_walls    {{ type omegaWallFunction; value uniform {om0:.4f}; }}
    wafer           {{ type omegaWallFunction; value uniform {om0:.4f}; }}
}}
"""


def _write_case_json_vices(case_dir: Path, vices_result,
                            flow_rate_slm: float, beta: float,
                            v_th: float, D_m: float, T_inlet: float,
                            pulse_time: float, purge_time: float,
                            turbulent: bool, Re: float):
    params = vices_result.params
    meta = {
        "solver":     "reactingFoam",
        "track":      2,
        "geometry_type": params.get('type', 'vices'),
        "turbulence": "kOmegaSST" if turbulent else "laminar",
        "csg":        vices_result.csg_description,
        "geometry":   params,
        "process": {
            "flow_rate_slm": flow_rate_slm,
            "beta":          beta,
            "v_th":          v_th,
            "D_m":           D_m,
            "T_inlet":       T_inlet,
            "pulse_time":    pulse_time,
            "purge_time":    purge_time,
        },
        "dimensionless": {"Re": Re},
    }
    with open(case_dir / "case_meta.json", "w") as f:
        json.dump(meta, f, indent=2)


def generate_case_vices(
    vices_result,
    case_dir:      str,
    flow_rate_slm: float = 2.0,
    beta:          float = 0.05,
    v_th:          float = 144.0,
    D_m:           float = D_TMA_N2,
    T_inlet:       float = T_REF,
    pulse_time:    float = 0.10,
    purge_time:    float = 0.10,
    dt:            float = 1e-4,
) -> str:
    """
    Generate a complete reactingFoam OpenFOAM case from a VICES geometry.
    Mirrors generate_case() but takes VICESResult instead of ShowerheadGeometry.

    Key differences from Track 1:
    - blockMeshDict sized from VICES mesh bounding box
    - snappyHexMeshDict references VICES region STLs
    - BCs use same patches: inlet / outlet / outerWalls / nozzle_walls / wafer
    """
    params     = vices_result.params
    D          = params.get('D', 0.002)
    D_plate    = params.get('D_plate', 0.150)
    n_nozzles  = params.get('n_nozzles', 1)

    out        = Path(case_dir)
    U_inlet    = _flow_rate_to_velocity(flow_rate_slm, D_plate)
    U_nozzle   = _nozzle_velocity(flow_rate_slm, D, n_nozzles)
    turbulent  = _is_turbulent(U_nozzle, D)
    Re         = _reynolds(U_nozzle, D)

    if out.exists():
        _has_results = any(
            True for d in out.iterdir()
            if d.is_dir() and _is_float_dir(d.name)
            and float(d.name) > 0 and (d / "U").exists()
        )
        if _has_results:
            return str(out)
        shutil.rmtree(out)

    (out / "0").mkdir(parents=True)
    (out / "constant" / "polyMesh").mkdir(parents=True)
    (out / "system").mkdir(parents=True)
    (out / "geometry").mkdir(parents=True)

    # ── 0/ fields — VICES-specific patch names ───────────────────────────
    (out / "0" / "U").write_text(_v2_field_U(U_inlet))
    (out / "0" / "p").write_text(_v2_field_p())
    (out / "0" / "T").write_text(_v2_field_T(T_inlet))
    (out / "0" / "TMA").write_text(_v2_field_TMA(pulse_time))
    (out / "0" / "N2").write_text(_v2_field_N2())
    if turbulent:
        (out / "0" / "k").write_text(_v2_field_k(U_nozzle, D))
        (out / "0" / "omega").write_text(_v2_field_omega(U_nozzle, D))

    # ── constant/ — identical to Track 1 ─────────────────────────────────
    (out / "constant" / "thermophysicalProperties").write_text(
        _thermophysicalProperties(T_inlet))
    (out / "constant" / "reactions").write_text(_reactions(beta, v_th, D_m))
    (out / "constant" / "momentumTransport").write_text(_momentumTransport(turbulent))
    (out / "constant" / "turbulenceProperties").write_text(
        _momentumTransport(turbulent).replace('"momentumTransport"', '"turbulenceProperties"'))
    (out / "constant" / "thermophysicalTransport").write_text(_thermophysicalTransport())

    # ── system/ — VICES-specific blockMesh + snappyHexMesh ───────────────
    (out / "system" / "blockMeshDict").write_text(_blockMeshDict_vices(vices_result))
    (out / "system" / "controlDict").write_text(_controlDict(pulse_time, purge_time, dt))
    (out / "system" / "fvSchemes").write_text(_fvSchemes(turbulent))
    (out / "system" / "fvSolution").write_text(_fvSolution(turbulent))

    # ── VICES region STLs ─────────────────────────────────────────────────
    stl_paths = _export_vices_stls(vices_result, out / "geometry")
    (out / "system" / "snappyHexMeshDict").write_text(
        _snappyHexMeshDict_vices(vices_result, stl_paths))

    # ── Metadata ──────────────────────────────────────────────────────────
    _write_case_json_vices(out, vices_result, flow_rate_slm, beta,
                           v_th, D_m, T_inlet, pulse_time, purge_time,
                           turbulent, Re)

    # ── run.sh ────────────────────────────────────────────────────────────
    turb_info = f"k-omega SST (Re={Re:.0f})" if turbulent else f"laminar (Re={Re:.0f})"
    stl_names = " ".join(p.name for p in stl_paths.values())
    run_sh = f"""#!/bin/bash
# Auto-generated run script — reactingFoam (Track 2 VICES)
# Case: {out.name}  |  Turbulence: {turb_info}
set -e
cd "$(dirname "$0")"

mkdir -p constant/triSurface
cp geometry/*.stl constant/triSurface/

echo "=== blockMesh ==="
blockMesh

echo "=== snappyHexMesh ==="
snappyHexMesh -overwrite

echo "=== reactingFoam ==="
reactingFoam

echo "=== Done: {out.name} ==="
"""
    run_path = out / "run.sh"
    run_path.write_text(run_sh)
    run_path.chmod(0o755)

    print(f"VICES case generated: {out}")
    print(f"  Type: {params.get('type','?')}  |  CSG: {vices_result.csg_description[:60]}...")
    print(f"  Turbulence: {turb_info}  |  n_nozzles: {n_nozzles}")
    return str(out)
