"""
openfoam/case_generator.py

Generates a complete aldFoam OpenFOAM case directory for a 3D showerhead
from a parameter dict. No m4/sed needed — all files are written from Python
f-strings so they are fully parametric and easy to inspect.

Fluid domain topology (bottom = z=0 = wafer plane):
    z = 0                → WAFER      (deposition surface, firstorder reaction BC)
    z = 0 … standoff     → STANDOFF   (free jet region)
    z = standoff         → PLATE_BOT  (bottom of distributor plate — wall)
    z = standoff+t_face  → PLATE_TOP  (top of plate — wall, faces plenum)
    nozzle cylinders     → NOZZLE     (firstorder reaction BC, sticking coeff β)
    z = standoff+t_face  → PLENUM     (mixing chamber)
    z = plenum top       → INLET      (gas enters here, uniform U, pulsed N1)
    outer cylinder       → OUTER_WALL (no-slip wall, or symmetry for large plates)

Usage
-----
    from openfoam.case_generator import generate_case
    from geometry.parametric import build_showerhead

    geo = build_showerhead({"D": 0.002, "pitch_over_D": 4.0})
    case_dir = generate_case(
        geo=geo,
        case_dir="openfoam/cases/case_001",
        flow_rate_slm=2.0,
        beta=0.05,
        v_th=144.0,
        pulse_time=0.1,
        purge_time=0.1,
        end_time=0.25,
    )
"""

from __future__ import annotations

import json
import math
import shutil
from pathlib import Path
from typing import Optional

import numpy as np

from geometry.mesh_export import export_stl
from geometry.parametric import ShowerheadGeometry


# ── physical constants ─────────────────────────────────────────────────────
# N2 carrier gas at ~120 °C (393 K), 1 atm
RHO_N2   = 1.12     # kg/m³
MU_N2    = 2.0e-5   # Pa·s
D_TMA_N2 = 2.5e-5   # m²/s   (TMA precursor diffusivity in N2)


# ══════════════════════════════════════════════════════════════════════════
# Velocity calculation
# ══════════════════════════════════════════════════════════════════════════

def _flow_rate_to_velocity(flow_rate_slm: float, D_plate: float) -> float:
    """Convert flow rate [slm] to mean inlet velocity [m/s] at plate inlet."""
    Q_m3s   = flow_rate_slm * 1e-3 / 60.0   # slm → m³/s
    A_inlet = math.pi * (D_plate / 2.0) ** 2
    return Q_m3s / A_inlet


def _nozzle_velocity(flow_rate_slm: float, D: float, n_holes: int) -> float:
    """Mean velocity at nozzle exit [m/s]."""
    Q_m3s    = flow_rate_slm * 1e-3 / 60.0
    A_nozzle = n_holes * math.pi * (D / 2.0) ** 2
    return Q_m3s / A_nozzle


# ══════════════════════════════════════════════════════════════════════════
# OpenFOAM file writers
# ══════════════════════════════════════════════════════════════════════════

_FOAM_HEADER = """\
/*--------------------------------*- C++ -*----------------------------------*\\
| Generated by cfd-ald-app/openfoam/case_generator.py                        |
\\*---------------------------------------------------------------------------*/
FoamFile
{{
    version     2.0;
    format      ascii;
    class       {cls};
    location    "{location}";
    object      {obj};
}}
"""

def _header(cls: str, location: str, obj: str) -> str:
    return _FOAM_HEADER.format(cls=cls, location=location, obj=obj)


# ── blockMeshDict ─────────────────────────────────────────────────────────

def _blockMeshDict(geo: ShowerheadGeometry) -> str:
    p        = geo.params
    R        = p["D_plate"] / 2.0
    z_total  = p["standoff"] + p["t_face"] + p["H_plenum"]
    # cells: target ~3 mm cell size in background; snappyHexMesh refines further
    nx = max(20, int(2 * R / 0.003))
    ny = nx
    nz = max(10, int(z_total / 0.003))

    return _header("dictionary", "system", "blockMeshDict") + f"""
convertToMeters 1;

vertices
(
    ({-R:.6f} {-R:.6f} 0)          // 0
    ( {R:.6f} {-R:.6f} 0)          // 1
    ( {R:.6f}  {R:.6f} 0)          // 2
    ({-R:.6f}  {R:.6f} 0)          // 3
    ({-R:.6f} {-R:.6f} {z_total:.6f})  // 4
    ( {R:.6f} {-R:.6f} {z_total:.6f})  // 5
    ( {R:.6f}  {R:.6f} {z_total:.6f})  // 6
    ({-R:.6f}  {R:.6f} {z_total:.6f})  // 7
);

blocks
(
    hex (0 1 2 3 4 5 6 7) ({nx} {ny} {nz}) simpleGrading (1 1 1)
);

edges ();

boundary
(
    inlet
    {{
        type patch;
        faces ( (4 5 6 7) );
    }}
    outlet
    {{
        type patch;
        faces ( (0 1 2 3) );
    }}
    outerWalls
    {{
        type wall;
        faces
        (
            (0 1 5 4)
            (1 2 6 5)
            (2 3 7 6)
            (3 0 4 7)
        );
    }}
);

mergePatchPairs ();
"""


# ── snappyHexMeshDict ─────────────────────────────────────────────────────

def _snappyHexMeshDict(geo: ShowerheadGeometry, stl_dir: str) -> str:
    p        = geo.params
    D        = p["D"]
    t_face   = p["t_face"]
    standoff = p["standoff"]
    R        = p["D_plate"] / 2.0
    z_total  = standoff + t_face + p["H_plenum"]

    # Refinement levels: nozzles need finest level (features at scale D)
    nozzle_level  = max(2, int(math.log2(0.003 / D)) + 1)
    plate_level   = max(1, nozzle_level - 1)

    # Inside-point: centre of plenum (always in fluid)
    inside_x = 0.0
    inside_y = 0.0
    inside_z = standoff + t_face + p["H_plenum"] * 0.5

    return _header("dictionary", "system", "snappyHexMeshDict") + f"""
castellatedMesh true;
snap            true;
addLayers       false;

geometry
{{
    nozzles.stl
    {{
        type triSurfaceMesh;
        name nozzle_walls;
    }}
    plenum.stl
    {{
        type triSurfaceMesh;
        name plenum_walls;
    }}
    standoff.stl
    {{
        type triSurfaceMesh;
        name standoff_walls;
    }}
    wafer_plane.stl
    {{
        type triSurfaceMesh;
        name wafer;
    }}
}}

castellatedMeshControls
{{
    maxLocalCells           2000000;
    maxGlobalCells          6000000;
    minRefinementCells      10;
    maxLoadUnbalance        0.10;
    nCellsBetweenLevels     2;

    features ();

    refinementSurfaces
    {{
        nozzle_walls
        {{
            level ({nozzle_level} {nozzle_level});
            patchInfo {{ type wall; }}
        }}
        plenum_walls
        {{
            level ({plate_level} {plate_level});
            patchInfo {{ type wall; }}
        }}
        standoff_walls
        {{
            level ({plate_level} {plate_level});
            patchInfo {{ type wall; }}
        }}
        wafer
        {{
            level ({plate_level} {plate_level});
            patchInfo {{ type wall; }}
        }}
    }}

    refinementRegions {{}}

    locationInMesh ({inside_x:.4f} {inside_y:.4f} {inside_z:.4f});
    allowFreeStandingZoneFaces true;
}}

snapControls
{{
    nSmoothPatch        3;
    tolerance           2.0;
    nSolveIter          30;
    nRelaxIter          5;
    nFeatureSnapIter    10;
    implicitFeatureSnap false;
    explicitFeatureSnap true;
    multiRegionFeatureSnap false;
}}

addLayersControls
{{
    relativeSizes       true;
    layers {{}}
    expansionRatio      1.2;
    finalLayerThickness 0.3;
    minThickness        0.1;
    nGrow               0;
    featureAngle        60;
    nRelaxIter          3;
    nSmoothSurfaceNormals 1;
    nSmoothNormals      3;
    nSmoothThickness    10;
    maxFaceThicknessRatio 0.5;
    maxThicknessToMedialRatio 0.3;
    minMedialAxisAngle  90;
    nBufferCellsNoExtrude 0;
    nLayerIter          50;
}}

meshQualityControls
{{
    maxNonOrtho         65;
    maxBoundarySkewness 20;
    maxInternalSkewness 4;
    maxConcave          80;
    minVol              1e-13;
    minTetQuality       1e-30;
    minArea             -1;
    minTwist            0.02;
    minDeterminant      0.001;
    minFaceWeight       0.05;
    minVolRatio         0.01;
    minTriangleTwist    -1;
    nSmoothScale        4;
    errorReduction      0.75;
    relaxed
    {{
        maxNonOrtho     75;
    }}
}}

writeFlags
(
    scalarLevels
    faceZones
    cellZones
);

mergeTolerance 1e-6;
"""


# ── controlDict ───────────────────────────────────────────────────────────

def _controlDict(end_time: float, dt: float = 1e-4,
                 write_interval: float = 0.01) -> str:
    return _header("dictionary", "system", "controlDict") + f"""
application     aldFoam;

startFrom       startTime;
startTime       0;

stopAt          endTime;
endTime         {end_time:.4f};

deltaT          {dt:.2e};

writeControl    adjustableRunTime;
writeInterval   {write_interval:.4f};

purgeWrite      0;
writeFormat     ascii;
writePrecision  8;
writeCompression off;

timeFormat      general;
timePrecision   6;

runTimeModifiable yes;
adjustTimeStep  yes;
maxCo           0.5;
maxDeltaT       {dt * 10:.2e};
"""


# ── transportProperties ───────────────────────────────────────────────────

def _transportProperties(D_m: float, v_th: float) -> str:
    return _header("dictionary", "constant", "transportProperties") + f"""
// Carrier gas (N2) + precursor transport
// D1:  precursor mass diffusivity in carrier gas [m²/s]
// vth: mean thermal velocity of precursor molecules [m/s]
//      = sqrt(8 k_B T / (pi m))   for TMA at ~120 C: ~144 m/s

D1    D1  [ 0 2 -1 0 0 0 0 ]  {D_m:.4e};
vth   vth [ 0 1 -1 0 0 0 0 ]  {v_th:.2f};
"""


# ── processData ───────────────────────────────────────────────────────────

def _processData(pulse_time: float, purge_time: float) -> str:
    return _header("dictionary", "constant", "processData") + f"""
// ALD pulse / purge timing
// Pulse: precursor on for [0, pulse_time]
// Purge: precursor off for [pulse_time, pulse_time + purge_time]

pulseTime   {pulse_time:.4f};   // [s]  precursor ON duration
purgeTime   {purge_time:.4f};   // [s]  purge (inert gas) duration
cycleTime   {pulse_time + purge_time:.4f};   // [s]  total ALD half-cycle
"""


# ── Boundary condition files ───────────────────────────────────────────────

def _field_U(U_inlet: float) -> str:
    return _header("volVectorField", "0", "U") + f"""
dimensions      [0 1 -1 0 0 0 0];

internalField   uniform (0 0 {-U_inlet:.6f});   // downward flow (-z)

boundaryField
{{
    inlet
    {{
        type            fixedValue;
        value           uniform (0 0 {-U_inlet:.6f});
    }}
    outlet
    {{
        type            zeroGradient;
    }}
    outerWalls
    {{
        type            noSlip;
    }}
    nozzle_walls
    {{
        type            noSlip;
    }}
    plenum_walls
    {{
        type            noSlip;
    }}
    standoff_walls
    {{
        type            noSlip;
    }}
    wafer
    {{
        type            noSlip;
    }}
}}
"""


def _field_p() -> str:
    return _header("volScalarField", "0", "p") + """
dimensions      [0 2 -2 0 0 0 0];

internalField   uniform 0;

boundaryField
{
    inlet
    {
        type            zeroGradient;
    }
    outlet
    {
        type            fixedValue;
        value           uniform 0;
    }
    outerWalls      { type noSlip; value uniform 0; }
    nozzle_walls    { type zeroGradient; }
    plenum_walls    { type zeroGradient; }
    standoff_walls  { type zeroGradient; }
    wafer           { type zeroGradient; }
}
"""


def _field_N1(pulse_time: float, beta: float) -> str:
    """Precursor concentration — pulsed inlet, firstorder reaction at walls."""
    purge_start = pulse_time
    purge_end   = purge_start + 1e-3   # small ramp down

    return _header("volScalarField", "0", "N1") + f"""
dimensions      [0 0 0 0 0 0 0];   // normalised number density

internalField   uniform 0;

boundaryField
{{
    inlet
    {{
        // Pulsed precursor: on for [0, pulse_time], off (purge) after
        type            uniformFixedValue;
        uniformValue    table
        (
            (0                  0)
            (1e-4               1)
            ({pulse_time:.4f}   1)
            ({purge_start:.4f}  1)
            ({purge_end:.4f}    0)
            (1e6                0)
        );
    }}
    outlet
    {{
        type            zeroGradient;
    }}
    nozzle_walls
    {{
        type            firstorder;
        betaField       beta;
        diffCoeff       D1;
        vth             vth;
        value           uniform 0;
    }}
    plenum_walls    {{ type zeroGradient; }}
    outerWalls      {{ type zeroGradient; }}
    standoff_walls  {{ type zeroGradient; }}
    wafer
    {{
        type            firstorder;
        betaField       beta;
        diffCoeff       D1;
        vth             vth;
        value           uniform 0;
    }}
}}
"""


def _field_beta(beta: float) -> str:
    return _header("volScalarField", "0", "beta") + f"""
dimensions      [0 0 0 0 0 0 0];

internalField   uniform 0;

boundaryField
{{
    nozzle_walls
    {{
        type            fixedValue;
        value           uniform {beta:.4f};
    }}
    wafer
    {{
        type            fixedValue;
        value           uniform {beta:.4f};
    }}
    inlet           {{ type zeroGradient; }}
    outlet          {{ type zeroGradient; }}
    plenum_walls    {{ type zeroGradient; }}
    standoff_walls  {{ type zeroGradient; }}
    outerWalls      {{ type zeroGradient; }}
}}
"""


def _field_cov() -> str:
    return _header("volScalarField", "0", "cov") + """
dimensions      [0 0 0 0 0 0 0];

internalField   uniform 0;

boundaryField
{
    nozzle_walls    { type fixedValue; value uniform 0; }
    wafer           { type fixedValue; value uniform 0; }
    inlet           { type zeroGradient; }
    outlet          { type zeroGradient; }
    plenum_walls    { type zeroGradient; }
    standoff_walls  { type zeroGradient; }
    outerWalls      { type zeroGradient; }
}
"""


def _field_growth() -> str:
    return _header("volScalarField", "0", "growth") + """
dimensions      [0 0 0 0 0 0 0];

internalField   uniform 0;

boundaryField
{
    nozzle_walls    { type fixedValue; value uniform 0; }
    wafer           { type fixedValue; value uniform 0; }
    inlet           { type zeroGradient; }
    outlet          { type zeroGradient; }
    plenum_walls    { type zeroGradient; }
    standoff_walls  { type zeroGradient; }
    outerWalls      { type zeroGradient; }
}
"""


def _field_Exp1(pulse_time: float) -> str:
    return _header("volScalarField", "0", "Exp1") + f"""
// Exposure = time-integral of N1 at surface
// Initialised to 0; accumulated by aldFoam solver during pulse

dimensions      [0 0 1 0 0 0 0];

internalField   uniform 0;

boundaryField
{{
    nozzle_walls    {{ type fixedValue; value uniform 0; }}
    wafer           {{ type fixedValue; value uniform 0; }}
    inlet           {{ type zeroGradient; }}
    outlet          {{ type zeroGradient; }}
    plenum_walls    {{ type zeroGradient; }}
    standoff_walls  {{ type zeroGradient; }}
    outerWalls      {{ type zeroGradient; }}
}}
"""


# ══════════════════════════════════════════════════════════════════════════
# Case metadata
# ══════════════════════════════════════════════════════════════════════════

def _write_case_json(case_dir: Path, geo: ShowerheadGeometry,
                     flow_rate_slm: float, beta: float,
                     v_th: float, D_m: float,
                     pulse_time: float, purge_time: float):
    """Write a JSON summary of the case for easy reference and postprocessing."""
    from physics.calculator import (
        reynolds, schmidt, peclet_mass, damkohler, k_rxn_from_sticking
    )
    p = geo.params
    U_nozzle = _nozzle_velocity(flow_rate_slm, p["D"], geo.n_holes)
    k_rxn    = k_rxn_from_sticking(beta, v_th)

    meta = {
        "geometry":   p,
        "n_holes":    geo.n_holes,
        "pattern":    geo.topology.pattern.value,
        "open_area":  geo.open_area_frac,
        "process": {
            "flow_rate_slm": flow_rate_slm,
            "beta":          beta,
            "v_th":          v_th,
            "D_m":           D_m,
            "pulse_time":    pulse_time,
            "purge_time":    purge_time,
        },
        "derived": {
            "U_inlet":   _flow_rate_to_velocity(flow_rate_slm, p["D_plate"]),
            "U_nozzle":  U_nozzle,
            "k_rxn":     k_rxn,
            "Re":        reynolds(RHO_N2, U_nozzle, p["D"], MU_N2),
            "Sc":        schmidt(MU_N2, RHO_N2, D_m),
            "Pe_m":      peclet_mass(
                             reynolds(RHO_N2, U_nozzle, p["D"], MU_N2),
                             schmidt(MU_N2, RHO_N2, D_m)
                         ),
            "Da":        damkohler(k_rxn, p["D"], U_nozzle),
        },
    }
    with open(case_dir / "case_meta.json", "w") as f:
        json.dump(meta, f, indent=2)


# ══════════════════════════════════════════════════════════════════════════
# Main entry point
# ══════════════════════════════════════════════════════════════════════════

def generate_case(
    geo:            ShowerheadGeometry,
    case_dir:       str,
    flow_rate_slm:  float = 2.0,
    beta:           float = 0.05,
    v_th:           float = 144.0,
    D_m:            float = D_TMA_N2,
    pulse_time:     float = 0.10,
    purge_time:     float = 0.10,
    end_time:       Optional[float] = None,
    dt:             float = 1e-4,
) -> str:
    """
    Generate a complete OpenFOAM case directory for aldFoam.

    Parameters
    ----------
    geo            : ShowerheadGeometry from geometry.parametric.build_showerhead()
    case_dir       : output directory path
    flow_rate_slm  : total volumetric flow rate [standard L/min]
    beta           : sticking coefficient [0–1]
    v_th           : precursor thermal velocity [m/s]
    D_m            : precursor mass diffusivity [m²/s]
    pulse_time     : ALD precursor pulse duration [s]
    purge_time     : purge (inert gas) duration [s]
    end_time       : simulation end time [s] (default: pulse + purge)
    dt             : initial time step [s]

    Returns
    -------
    str  path to the case directory
    """
    p   = geo.params
    out = Path(case_dir)

    if out.exists():
        shutil.rmtree(out)

    # Create directory structure
    (out / "0").mkdir(parents=True)
    (out / "constant" / "polyMesh").mkdir(parents=True)
    (out / "system").mkdir(parents=True)
    (out / "geometry").mkdir(parents=True)

    end_t = end_time or (pulse_time + purge_time + 0.05)
    U_inlet = _flow_rate_to_velocity(flow_rate_slm, p["D_plate"])

    # ── Write 0/ fields ───────────────────────────────────────────────────
    fields = {
        "U":      _field_U(U_inlet),
        "p":      _field_p(),
        "N1":     _field_N1(pulse_time, beta),
        "beta":   _field_beta(beta),
        "cov":    _field_cov(),
        "growth": _field_growth(),
        "Exp1":   _field_Exp1(pulse_time),
    }
    for name, content in fields.items():
        (out / "0" / name).write_text(content)

    # ── Write constant/ ───────────────────────────────────────────────────
    (out / "constant" / "transportProperties").write_text(
        _transportProperties(D_m, v_th))
    (out / "constant" / "processData").write_text(
        _processData(pulse_time, purge_time))

    # Copy static surfaceProcesses from template
    static_src = Path(__file__).parent / "showerhead_3d" / "constant" / "surfaceProcesses"
    if static_src.exists():
        shutil.copy(static_src, out / "constant" / "surfaceProcesses")

    # ── Write system/ ─────────────────────────────────────────────────────
    (out / "system" / "blockMeshDict").write_text(_blockMeshDict(geo))
    (out / "system" / "controlDict").write_text(_controlDict(end_t, dt))
    (out / "system" / "snappyHexMeshDict").write_text(
        _snappyHexMeshDict(geo, str(out / "geometry")))

    # Copy static fvSchemes, fvSolution, decomposeParDict
    for fname in ["fvSchemes", "fvSolution", "decomposeParDict"]:
        src = Path(__file__).parent / "showerhead_3d" / "system" / fname
        if src.exists():
            shutil.copy(src, out / "system" / fname)

    # ── Export STL geometry ───────────────────────────────────────────────
    export_stl(geo, str(out / "geometry"), combined=False)

    # ── Write case metadata JSON ──────────────────────────────────────────
    _write_case_json(out, geo, flow_rate_slm, beta, v_th, D_m,
                     pulse_time, purge_time)

    # ── Write run script ──────────────────────────────────────────────────
    run_sh = f"""#!/bin/bash
# Auto-generated run script for aldFoam
# Case: {out.name}
set -e
cd "$(dirname "$0")"

echo "=== blockMesh ==="
blockMesh

echo "=== snappyHexMesh ==="
snappyHexMesh -overwrite

echo "=== aldFoam ==="
aldFoam

echo "=== Done: {out.name} ==="
"""
    run_path = out / "run.sh"
    run_path.write_text(run_sh)
    run_path.chmod(0o755)

    print(f"Case generated: {out}")
    print(f"  U_inlet = {U_inlet:.4f} m/s | beta = {beta} | pulse = {pulse_time}s")
    return str(out)
